# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_funds', models.IntegerField(default=0)),
                ('available_funds', models.IntegerField(default=0)),
                ('SSN', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='date started')),
                ('order_type', models.CharField(choices=[('Limit', 'Limit')], max_length=20)),
                ('bidask', models.CharField(choices=[('BID', 'BID'), ('ASK', 'ASK')], max_length=3)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('order_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Possessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_account_id', to='exchange.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('volume', models.IntegerField(default=0)),
                ('inner_bid', models.IntegerField(default=0)),
                ('inner_ask', models.IntegerField(default=0)),
                ('fmv', models.IntegerField(default=0)),
                ('security_accounts', models.ManyToManyField(blank=True, to='exchange.Account')),
                ('security_orders', models.ManyToManyField(blank=True, to='exchange.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('ask_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ask_account', to='exchange.Account')),
                ('bid_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bid_account', to='exchange.Account')),
                ('security_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_security_id', to='exchange.Security')),
            ],
        ),
        migrations.AddField(
            model_name='possessions',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_security_id', to='exchange.Security'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Security'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_orders',
            field=models.ManyToManyField(blank=True, to='exchange.Order'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_securities',
            field=models.ManyToManyField(blank=True, to='exchange.Security'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='possessions',
            unique_together=set([('account_id', 'security_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('SSN', 'id')]),
        ),
    ]
