# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_securities',
            field=models.ManyToManyField(blank=True, to='exchange.Possessions'),
        ),
    ]
