# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-16 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0004_security_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='possessions',
            old_name='amount',
            new_name='available_amount',
        ),
        migrations.AddField(
            model_name='possessions',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
