# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0005_auto_20160416_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='security',
            name='security_accounts',
        ),
        migrations.RemoveField(
            model_name='security',
            name='security_orders',
        ),
        migrations.AddField(
            model_name='security',
            name='name',
            field=models.CharField(default='NameGoesHere', max_length=25),
        ),
    ]
