# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-17 01:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20160416_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 17, 1, 49, 2, 503506, tzinfo=utc)),
        ),
    ]
