# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0006_auto_20160329_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='funds',
            new_name='available_funds',
        ),
        migrations.AddField(
            model_name='account',
            name='total_funds',
            field=models.IntegerField(default=0),
        ),
    ]
