# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_auto_20160410_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Limit', 'Limit')], max_length=20),
        ),
    ]
