# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0007_trade_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
