# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 06:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20160410_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Security')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('ask_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ask_account', to='exchange.Account')),
                ('bid_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='bid_account', to='exchange.Account')),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exchange.Security')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='posessions',
            unique_together=set([('account', 'security')]),
        ),
    ]
