# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0008_auto_20160417_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='available_funds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_funds',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='security',
            name='fmv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='security',
            name='inner_ask',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='security',
            name='inner_bid',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trade',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
