# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('funds', models.IntegerField(default=0)),
                ('SSN', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('account_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('start_time', models.DateTimeField(verbose_name='date started')),
                ('order_type', models.CharField(choices=[('Fill or Kill', 'Fill or Kill')], max_length=20)),
                ('bidask', models.CharField(choices=[('BID', 'BID'), ('ASK', 'ASK')], max_length=3)),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('order_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('order_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('symbol', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('volume', models.IntegerField(default=0)),
                ('inner_bid', models.IntegerField(default=0)),
                ('inner_ask', models.IntegerField(default=0)),
                ('fmv', models.IntegerField(default=0)),
                ('security_accounts', models.ManyToManyField(blank=True, to='exchange.Account')),
                ('security_orders', models.ManyToManyField(blank=True, to='exchange.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_security',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exchange.Security'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_orders',
            field=models.ManyToManyField(blank=True, to='exchange.Order'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_securities',
            field=models.ManyToManyField(blank=True, to='exchange.Security'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('SSN', 'account_num')]),
        ),
    ]
