# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='SSN',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_num',
        ),
    ]
