# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-11 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0011_auto_20160411_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posessions',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_account_id', to='exchange.Account'),
        ),
        migrations.AlterField(
            model_name='posessions',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_security_id', to='exchange.Security'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='security_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='trade_security_id', to='exchange.Security'),
        ),
    ]
